DATA:
  DATASET: cifar100
  IMG_SIZE: 224
MODEL:
  TYPE: vit
  NAME: ViT_Tiny_16_224_cifar100
  NUM_CLASSES: 100
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 5e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
