DATA:
  DATASET: tiny-imagenet
  IMG_SIZE: 224
MODEL:
  TYPE: cait_xxs
  NAME: cait_xxs12_16_224_tiny_imagenet
  NUM_CLASSES: 200
  CaiT_XXS:
    DEPTHS: 12
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 5e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
