DATA:
  DATASET: cifar10
  IMG_SIZE: 224
MODEL:
  TYPE: cait_xxs
  NAME: cait_xxs12_16_224_cifar10
  NUM_CLASSES: 10
  CaiT_XXS:
    DEPTHS: 12
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  BASE_LR: 5e-4
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
